# Generated by Django 2.1.1 on 2019-05-11 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Umiejętności Oferty')),
                ('year', models.IntegerField(blank=True, default=0, null=True, verbose_name='Oczekiwane Zarobki')),
                ('rated', models.CharField(blank=True, max_length=200, null=True, verbose_name='Umiejętności Oferty')),
                ('released', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered at')),
                ('runtime', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('writer', models.CharField(blank=True, max_length=200, null=True)),
                ('plot', models.CharField(blank=True, max_length=2000, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('awards', models.CharField(blank=True, max_length=200, null=True)),
                ('poster', models.URLField()),
                ('metascore', models.CharField(blank=True, max_length=200, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('imdb_votes', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('imbd_id', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('dvd', models.DateTimeField(blank=True, null=True, verbose_name='DVD release date')),
                ('box_office', models.CharField(blank=True, max_length=200, null=True)),
                ('production', models.CharField(blank=True, max_length=200, null=True, verbose_name='Umiejętności Oferty')),
                ('website', models.URLField()),
                ('response', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(blank=True, to='movies.ActorModel')),
                ('language', models.ManyToManyField(blank=True, to='movies.LanguageModel')),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='movies.RatingModel'),
        ),
    ]
